Repository wearesho-team/pvbki, pull requests merged in 2018-10, with the labels that each got.

#5 Fix dependencies compatibilities
  composer.json
  composer.lock
Labels: bug, enhancement

#4 phpunit configuration
  phpunit.xml
Labels: enhancement

#6 configuration implementation
  composer.json
  composer.lock
  src/Config.php
  src/ConfigInterface.php
  src/EnvironmentConfig.php
  src/Exceptions/UnsupportedMode.php
  tests/Extend/ConfigTestCase.php
  tests/Unit/ConfigTest.php
  tests/Unit/EnvironmentConfigTest.php
  tests/Unit/Exceptions/InvalidModeExceptionTest.php
Labels: enhancement

#8 Change license to MIT
  LICENSE
  README.md
  composer.json
Labels: enhancement

#11 Add documentation for config usage
  README.md
Labels: enhancement

#12 Implementation of identifications for requests
  src/Exceptions/IdentificationDataValidation.php
  src/Identifications/Complex.php
  src/Identifications/Drfo.php
  src/Identifications/Okpo.php
  src/Identifications/Passport.php
  src/Identifications/SubjectInterface.php
  src/Identifications/SubjectTrait.php
  tests/Unit/Exceptions/IdentificationDataValidationTest.php
  tests/Unit/IdentificationsTest.php
Labels: enhancement

#7 Base collection with strong type
  src/BaseCollection.php
  tests/Unit/BaseCollectionTest.php
Labels: enhancement

#13 Xsd schemas for statement reports
  data/schemas/StatementPlusSchema.xml
  data/schemas/StatementSchema.xml
Labels: enhancement

#14 Statement reports mocks
  tests/Mocks/StatementReport.xml
  tests/Mocks/StatementReportPlus.xml
Labels: enhancement

#18 Implement base element for statement elements
  src/Infrastructure/Element.php
  src/Interrelations/ElementInterface.php
  tests/Unit/Infrastructure/ElementTest.php
Labels: enhancement

#21 Implement translation class for elements' arguments
  src/Sentence/Translation.php
  tests/Unit/Sentence/TranslationTest.php
Labels: enhancement

#19 Address element/collection
  src/Collections/Addresses.php
  src/Elements/Address.php
  tests/Unit/Collections/AddressesTest.php
  tests/Unit/Elements/AddressTest.php
Labels: enhancement

#36 Import logic implementation
  README.md
  src/Config.php
  src/Enums/StatementType.php
  src/EnvironmentConfig.php
  src/Identifications/Complex.php
  src/Identifications/Drfo.php
  src/Identifications/Okpo.php
  src/Identifications/Passport.php
  src/Infrastructure/StatementRequestTrait.php
  src/Infrastructure/SubjectTrait.php
  src/Interrelations/ConfigInterface.php
  src/Interrelations/ServiceInterface.php
  src/Interrelations/StatementRequestInterface.php
  src/Interrelations/SubjectInterface.php
  src/RequestResponsePair.php
  src/Service.php
  src/StatementRequest.php
  tests/Extend/ConfigTestCase.php
  tests/Unit/EnvironmentConfigTest.php
  tests/Unit/RequestResponsePairTest.php
  tests/Unit/ServiceTest.php
  tests/Unit/StatementRequestTest.php
Labels: enhancement

#32 Implement Subject element
  src/Elements/Subject.php
  tests/Unit/Elements/SubjectTest.php
Labels: enhancement

#31 Scoring element
  src/Elements/Scoring.php
  tests/Unit/Elements/ScoringTest.php
Labels: enhancement

#41 Integrate base-collection as dependency
  composer.json
  composer.lock
  src/Collections/Addresses.php
  src/Collections/Collaterals.php
  src/Collections/Contracts.php
  src/Collections/Dependants.php
  src/Collections/Errors.php
  src/Collections/Events.php
  src/Collections/Identifiers.php
  src/Collections/MonthlyIncomes.php
  src/Collections/Records.php
  src/Collections/Summaries.php
  src/Infrastructure/BaseCollection.php
  tests/Unit/BaseCollectionTest.php
Labels: enhancement

#42 Implement communication type enum
  src/Enums/CommunicationType.php
  tests/Unit/Enums/CommunicationTypeTest.php
Labels: enhancement

#43 Implement classification enum
  src/Enums/Classification.php
  tests/Unit/Enums/ClassificationTest.php
Labels: enhancement

#46 Implement base enum that can contain null
  src/Enums/CommunicationType.php
  src/Infrastructure/Enum.php
  tests/Unit/Enums/CommunicationTypeTest.php
Labels: enhancement

#22 Communication element/collection
  src/Collections/Communications.php
  src/Elements/Communication.php
  tests/Unit/Collections/CommunicationsTest.php
  tests/Unit/Elements/CommunicationTest.php
Labels: enhancement

#44 Implement category enum
  src/Enums/Category.php
  tests/Unit/Enums/CategoryTest.php
Labels: enhancement, wontfix

#45 Implement address type enum
  src/Enums/AddressType.php
  tests/Unit/Enums/AddressTypeTest.php
Labels: enhancement

#47 Fix enums
  src/Enums/AddressType.php
  src/Enums/Category.php
  src/Enums/Classification.php
  src/Enums/CommunicationType.php
  src/Enums/StatementType.php
  src/Infrastructure/Enum.php
  src/Interrelations/NullableEnum.php
  tests/Unit/Enums/AddressTypeTest.php
  tests/Unit/Enums/CategoryTest.php
Labels: enhancement

#48 Implement and integrate Collateral type enum
  src/Elements/Collateral.php
  src/Enums/CollateralType.php
  tests/Unit/Elements/CollateralTest.php
Labels: enhancement

#54 Fix use namespace cases in Contract
  src/Elements/Contract.php
Labels: bug, enhancement

#49 Implement and integrate Contract type enum
  src/Elements/Contract.php
  src/Enums/ContractType.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/ContractTypeTest.php
Labels: enhancement

#50 Implement and integrate credit purpose type enum
  src/Elements/Contract.php
  src/Enums/CreditPurpose.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/CreditPurposeTest.php
Labels: enhancement

#51 Implement and integrate Credit usage enum
  src/Elements/Record.php
  src/Enums/CreditUsage.php
  tests/Unit/Elements/RecordTest.php
  tests/Unit/Enums/CreditUsageTest.php
Labels: enhancement

#52 Implement and integrate Economic activity enum
  src/Elements/Subject.php
  src/Enums/EconomicActivity.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/EconomicActivityTest.php
Labels: enhancement

#56 Implement and integrate Entity enum
  src/Elements/Subject.php
  src/Enums/Entity.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/EntityTest.php
Labels: enhancement

#62 Implement and integrate ownership enum
  src/Elements/Subject.php
  src/Enums/Ownership.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/OwnershipTest.php
Labels: enhancement

#57 Implement and integrate Gender enum
  src/Elements/Subject.php
  src/Enums/Gender.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/GenderTest.php
Labels: enhancement

#59 Implement and integrate Marital status enum
  src/Elements/Subject.php
  src/Enums/MaritalStatus.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/MaritalStatusTest.php
Labels: enhancement

#55 Implement and integrate Employee count enum
  src/Elements/Subject.php
  src/Enums/EmployeeCount.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/EmployeeCountTest.php
Labels: enhancement

#63 Fix const names for collateral types
  src/Enums/CollateralType.php
  tests/Unit/Elements/CollateralTest.php
Labels: enhancement

#58 Implement and integrate Identification type enum
  src/Elements/Collateral.php
  src/Enums/IdentificationType.php
  tests/Unit/Elements/CollateralTest.php
  tests/Unit/Enums/IdentificationTypeTest.php
Labels: enhancement

#60 Implement and integrate Subject negative status enum
  src/Elements/Subject.php
  src/Enums/SubjectNegativeStatus.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/SubjectNegativeStatusTest.php
Labels: enhancement

#61 Implement and integrate Contract negative status enum
  src/Elements/Contract.php
  src/Enums/ContractNegativeStatus.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/ContractNegativeStatusTest.php
Labels: enhancement

#64 Implement and integrate Payment method enum
  src/Elements/Contract.php
  src/Enums/PaymentMethod.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/PaymentMethodTest.php
Labels: enhancement

#66 Implement and integrate Phase enum
  src/Elements/Contract.php
  src/Enums/Phase.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/PhaseTest.php
Labels: enhancement

#67 Set SubjectNegativeStatus enum as final
  src/Enums/SubjectNegativeStatus.php
Labels: enhancement

#65 Implement and integrate Payment period enum
  src/Elements/Contract.php
  src/Enums/PaymentPeriod.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/PaymentPeriodTest.php
Labels: enhancement

#68 Implement and integrate Residency enum
  src/Elements/Subject.php
  src/Enums/Residency.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/ResidencyTest.php
Labels: enhancement

#69 Implement and integrate Status enum
  src/Elements/Subject.php
  src/Enums/Status.php
  tests/Unit/Elements/SubjectTest.php
  tests/Unit/Enums/StatusTest.php
Labels: enhancement

#70 Implement and integrate Role enum
  src/Elements/Contract.php
  src/Enums/Role.php
  tests/Unit/Elements/ContractTest.php
  tests/Unit/Enums/RoleTest.php
Labels: enhancement

#71 Remove nullable operator for type hint Translation
  src/Elements/Address.php
  src/Elements/Collateral.php
  src/Elements/Identifier.php
  src/Elements/Record.php
  src/Elements/Subject.php
Labels: enhancement

#72 Fixed enum types for elements
  src/Elements/Address.php
  src/Elements/Identifier.php
  src/Elements/Subject.php
  src/Enums/AddressType.php
  tests/Unit/Elements/AddressTest.php
  tests/Unit/Elements/IdentifierTest.php
  tests/Unit/Elements/SubjectTest.php
Labels: bug

#74 Fix type of citizenship due to lack of enum
  src/Elements/Subject.php
  tests/Unit/Elements/SubjectTest.php
Labels: bug

#73 Change type hint for category to enum type
  src/Elements/Summary.php
  tests/Unit/Elements/SummaryTest.php
Labels: bug, enhancement

#75 Report statement
  src/StatementReport.php
  tests/Unit/StatementReportTest.php
Labels: enhancement

#76 Set opportunity to set null value to enum
  src/Enums/AddressType.php
  src/Enums/Category.php
  src/Enums/Classification.php
  src/Enums/CollateralType.php
  src/Enums/CommunicationType.php
  src/Enums/ContractNegativeStatus.php
  src/Enums/ContractType.php
  src/Enums/CreditPurpose.php
  src/Enums/CreditUsage.php
  src/Enums/EconomicActivity.php
  src/Enums/Education.php
  src/Enums/EmployeeCount.php
  src/Enums/Entity.php
  src/Enums/Gender.php
  src/Enums/IdentificationType.php
  src/Enums/MaritalStatus.php
  src/Enums/Ownership.php
  src/Enums/PaymentMethod.php
  src/Enums/PaymentPeriod.php
  src/Enums/Phase.php
  src/Enums/Residency.php
  src/Enums/Role.php
  src/Enums/StatementType.php
  src/Enums/Status.php
  src/Enums/SubjectNegativeStatus.php
  src/Infrastructure/Enum.php
  tests/Unit/Enums/AddressTypeTest.php
  tests/Unit/Enums/CategoryTest.php
  tests/Unit/Enums/ClassificationTest.php
  tests/Unit/Enums/CommunicationTypeTest.php
  tests/Unit/Enums/ContractNegativeStatusTest.php
  tests/Unit/Enums/ContractTypeTest.php
  tests/Unit/Enums/CreditPurposeTest.php
  tests/Unit/Enums/CreditUsageTest.php
  tests/Unit/Enums/EconomicActivityTest.php
  tests/Unit/Enums/EducationTest.php
  tests/Unit/Enums/EmployeeCountTest.php
  tests/Unit/Enums/EntityTest.php
  tests/Unit/Enums/GenderTest.php
  tests/Unit/Enums/IdentificationTypeTest.php
  tests/Unit/Enums/MaritalStatusTest.php
  tests/Unit/Enums/OwnershipTest.php
  tests/Unit/Enums/PaymentMethodTest.php
  tests/Unit/Enums/PaymentPeriodTest.php
  tests/Unit/Enums/PhaseTest.php
  tests/Unit/Enums/ResidencyTest.php
  tests/Unit/Enums/RoleTest.php
  tests/Unit/Enums/StatusTest.php
  tests/Unit/Enums/SubjectNegativeStatusTest.php
  tests/Unit/Infrastructure/EnumTest.php
Labels: bug, enhancement, good first issue

#95 Uppdate enum package with fixed logic for null value
  composer.json
  composer.lock
  src/Enums/AddressType.php
  src/Enums/Category.php
  src/Enums/Classification.php
  src/Enums/CollateralType.php
  src/Enums/CommunicationType.php
  src/Enums/ContractNegativeStatus.php
  src/Enums/ContractType.php
  src/Enums/CreditPurpose.php
  src/Enums/CreditUsage.php
  src/Enums/EconomicActivity.php
  src/Enums/Education.php
  src/Enums/EmployeeCount.php
  src/Enums/Entity.php
  src/Enums/Gender.php
  src/Enums/IdentificationType.php
  src/Enums/MaritalStatus.php
  src/Enums/Ownership.php
  src/Enums/PaymentMethod.php
  src/Enums/PaymentPeriod.php
  src/Enums/Phase.php
  src/Enums/Residency.php
  src/Enums/Role.php
  src/Enums/StatementType.php
  src/Enums/Status.php
  src/Enums/SubjectNegativeStatus.php
  src/Infrastructure/Enum.php
  tests/Unit/Infrastructure/EnumTest.php
Labels: enhancement

#94 Fix use cases for communication element
  src/Elements/Communication.php
Labels: enhancement

#83 Fix use cases for base element
  src/Infrastructure/Element.php
Labels: enhancement

#82 Implement json serialize trait
  src/Infrastructure/Element.php
  src/Infrastructure/JsonSerializeTrait.php
  src/Sentence/Translation.php
Labels: enhancement

#81 Set Scoring object for report required
  src/StatementReport.php
Labels: bug, enhancement

#80 Make mock report full for tests
  tests/Mocks/StatementReportPlus.xml
Labels: enhancement

#79 Psr clean up for statement report test
  tests/Unit/StatementReportTest.php
Labels: enhancement

#78 Fix const values for Collaterla element
  src/Elements/Collateral.php
Labels: bug, enhancement

#84 Implement exception for invalid report xml structure
  src/Exceptions/InvalidReportXmlStructure.php
  tests/Unit/Exceptions/InvalidReportXmlStructureTest.php
Labels: enhancement

#97 Remove using logger from documentation example
  README.md
Labels: bug, enhancement

#40 Parser
  README.md
  src/Parser.php
  tests/Unit/ParserTest.php
Labels: enhancement

#96 Implement base exceptions
  src/Exception.php
  src/Exceptions/IdentificationDataValidation.php
  src/Exceptions/InvalidReportXmlStructure.php
  src/Exceptions/UnsupportedMode.php
  tests/Unit/Exceptions/IdentificationDataValidationTest.php
  tests/Unit/Exceptions/InvalidModeExceptionTest.php
  tests/Unit/Exceptions/InvalidReportXmlStructureTest.php
Labels: enhancement

#98 Add php7.3 to travis config for tests
  .travis.yml
Labels: enhancement

#99 Feature/json response example
  README.md
  data/response/example.json
Labels: enhancement
